### PR TITLE
initiate folder structure

### PR DESCRIPTION
**Pull request by wkCircle**
Initialized folder structure

Explanation:

Project Root:
`src/`: store source codes mainly .py files <br>
`experiments/`: store experiment files. I created an empty .ipynb file to keep Git able to detect and upload the folder.  <br>
`demo/`: store any files related to demos in the future. 
`docs/`: store documentation files, eg. conf.py or some sphinx related html, css etc will be stored in the folder.  <br>
- Note: `docs/conf.py` is intended to be used later for the configuration of sphinx for class/func documentation. <br>
`tests/`: store testing .py files for code base unit/integration... testing.  <br>
`.github/workflows`: store any workflow related to CI/CD. I created an empty `ci-build.yml` file, which is correctly identified by Github and complained some errors (not surprised).

Thanks for PR reviewing!

### CODE REVIEW

**Review by johnklee — DISMISSED** [review]
LGTM with a optional comment. The description of this PR is informative and helpful for others to learn more about how this repo is organized. You may rename the `docs.md` to be `README.md` and prepare a section to hold those information. In the future, I will put the steps and description on how we evaluate the model A (STT) in `README.md` too. Thanks!

**Comment by wkCircle** [comment]
Following John's suggestion, I have updated the naming of some md files.

**Comment by troublecat55** [comment]
LGTM, please merge so I don't need to rebase when setting up the CI tools

**Comment by wkCircle** [comment]
@troublecat55  needs review approval

**Review by troublecat55 — APPROVED** [review]

**Pull request merged**
